Improve RemoteAnalysisException reporting.
At least, we want to include the cause into the error message if general
communication failure happens!

Otherwise the user is blind and gets only this:
```
ERROR: Remote failure as CodeScene couldn't perform the delta analysis: org.jenkinsci.plugins.codescene.Domain.RemoteAnalysisException: Failed to send request to CodeScene at http://localhost:3003/projects/9/delta-analysis
```

The new reporting is at least slightly better:
```
ERROR: Remote failure as CodeScene couldn't perform the delta analysis: org.jenkinsci.plugins.codescene.Domain.RemoteAnalysisException: Failed to send request to CodeScene at http://localhost:3003/projects/9/delta-analysis
  cause: Connect to localhost:3003 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
  ```